### ISSUE TITLE
Mass Flux Bug at Downstream Boundary

### ISSUE THREAD

**Issue by jrutyna** [EcohydrologyTeam/ClearWater-riverine#47]
@jrutyna noticed that there was a mass balance issue in plan 241. Upon investigating it was determined that the mass flux variables for the downstream boundary was only using the boundary condition of 25 mg/L for this calculation and not using the concentration values in the cells next to the boundary. @sjordan29 should investigate further to determine how to fix this issue.

**Comment by sjordan29** [comment]
@jrutyna, I think this is fixed. I ran plan 241 again and got 0.04% error (see the comparison between the updated results on the left and the old results from your 30_Mass_Balance_JMR.ipynb notebook below):

<img width="698" alt="cw-r-mass-balance-fix" src="https://github.com/EcohydrologyTeam/ClearWater-riverine/assets/32182441/8a0d4433-3224-4962-979a-8c42b02bbb4c">

Does this look good to you? I can merge into main if yes.

**Comment by jrutyna** [comment]
@sjordan29: Yes, this looks like a significant improvement in the accounting for the mass flux across the faces at the boundary cells. Yes, please merge these commits to main.
