### ISSUE TITLE
Test 5, 10, 15 timestep for Larger Sumwere Creek

### ISSUE THREAD

**Issue by sjordan29** [EcohydrologyTeam/ClearWater-riverine#70]
We have increased the domain size of sumwere creek. Re-run the 100 everywhere test at 5, 10, 15 second timesteps and look at percent error in the output. This will help speed up demonstrations.

**Comment by sjordan29** [comment]
At first, I was getting very large percent errors (45% to >100%). I realized when I compared to the `_global_mass_bal_100_Ans` test that I had an error in the `_mass_flux` calculation method used in the `_global_mass_bal` calculation -- I wasn't multiplying by the change in time! I made those updates in commit [841cbfd12a1cc4f68e1dcef5703e46e98a88142e](https://github.com/EcohydrologyTeam/ClearWater-riverine/commit/841cbfd12a1cc4f68e1dcef5703e46e98a88142e) in `transport.py`

And I get the following:
![image](https://github.com/EcohydrologyTeam/ClearWater-riverine/assets/32182441/260f4082-2e76-4aae-8a3f-cc2a579207f9)


Looks like 15 second output should be fine to move forward with @jrutyna @aufdenkampe

**Comment by aufdenkampe** [comment]
@sjordan29, that's great to see!
I assume you saw a proposal improvement in the run time, right?

**Comment by sjordan29** [comment]
I never ran the 3-day 1-second simulation with Clearwater-Riverine alone (only with modules). Initializing and running these models took:
* 15-second: 3 min 21 sec
* 10-second: 5 min 10 sec
* 5-second: 10 min 05 sec

This would suggest that the 1-second output would take ~50-51 minutes, but not sure how the increase in memory might impact. We could run it without modules as a point of reference, but modules was the major slowdown with the 3-day simulation. 

Jason just sent a 30-second model for me to test, as well as a 5, 10, 15, and 30 second output for a scaled up fine mesh. Jason notes that the 30 sec output for the fine mesh violates the courant condition near the downstream end of the domain since the water is moving slightly more than 0.5 m/s and the cells in the channel are only 20 m^2. I will check dye results in this area to see if they make any sense.

**Comment by sjordan29** [comment]
The 30 second coarse mesh model had a percent error of 0.017549% and ran in 1 min, 43 seconds.

**Comment by jrutyna** [comment]
How do the volume errors compare among the four coarse mesh model simulations?

**Comment by aufdenkampe** [comment]
@sjordan29 & @jrutyna, this is great news! Running the 3-day, 30-sec time step, course mesh in 1 min, 43 seconds will be perfect for development and testing of ClearWater-modules.

We can then run the fine mesh at different time-step resolutions to explore the scaling curves for speed and memory, while still keeping being able to do common-sense evaluations of the TSM and NSM outputs.

**Comment by sjordan29** [comment]
@jrutyna, for the fine mesh, I'm seeing a larger percent volume error (-5.61%), so the mass error is pretty much leveling out at around that point as well.

**Comment by jrutyna** [comment]
Are you able to start riverine a day into the HEC-RAS simulation? i.e. do not use the first day of the results from the hdf5 file. I think the hydraulic spin-up period may be creating this problem...

**Comment by jrutyna** [comment]
If not, I can create a HEC-RAS simulation from a hot-start so you do not have to worry about that spin-up period.

**Comment by sjordan29** [comment]
Got it. Yeah, I can do that.

**Comment by sjordan29** [comment]
ok, started 12 hours in for the fine meshes and got the following results for the fine mesh -- the percent error in mass tracks pretty closely with the percent error in volume. And at 12 hours we hit <1% error for each.
![image](https://github.com/EcohydrologyTeam/ClearWater-riverine/assets/32182441/c7885a3f-9a67-4833-8c0d-67b6c6631be0)

These fine mesh models take longer to instantiate (reading data from HDF file) and run than the coarse mesh:
* 30-sec: ~5 min
* 15-sec: ~10 min
* 10-sec: ~15 min
* 5-sec: ~30 min

Guessing #61 could help with some of this. 

anything else we should test before closing this issue?

**Comment by jrutyna** [comment]
@sjordan29, did you compare the mass percent error from any of these simulations with its "answer" using concentrations of 100 mg/L everywhere?

**Comment by sjordan29** [comment]
Yes, all compared in the csv files here: https://github.com/EcohydrologyTeam/ClearWater-riverine/tree/test-larger-domain/examples/dev_sandbox/data

**Comment by jrutyna** [comment]
It looks like the flow boundary for Cold Spring Creek has mass and volume exiting the domain. I expected zero to leave the domain for Cold Spring Creek just like the Upstream flow boundary and the Power Plant flow boundary. Let's talk tomorrow.

**Comment by sjordan29** [comment]
@jrutyna, I made some code updates to address #73, and now the model will identify where there are erroneous faces associated with a boundary and filter those out of the `boundary_data` information associated with a model instance. It will notify users that it has identified this issue, though this should be transferred to logs when we add address #28:
![image](https://github.com/EcohydrologyTeam/ClearWater-riverine/assets/32182441/7d2a8b5e-c9a0-4b5d-8017-09a32ab0fda8)


This `boudary_data` is what is used in the `postproc_util` module, so there was no need to make any updates in that file.

This produces the following results for a 30 second model:

**Comment by sjordan29** [comment]
Still having trouble with interactive viz, but here's a gif with colors ranging from 99.5-100.5. Directly across from the cold creek you can see some wetting/drying. Otherwise, I don't see much down in the downstream. I can plot with a tighter range of colors, or @jrutyna you could try running [this notebook](https://github.com/EcohydrologyTeam/ClearWater-riverine/blob/test-larger-domain/examples/dev_sandbox/70_timestep_large_sumwere.ipynb) (specifically the fine mesh tests) and see if the dynamic viz is working for you or run any other tests. 

![5_min_99_100](https://github.com/EcohydrologyTeam/ClearWater-riverine/assets/32182441/dd919dfc-c5d3-4a10-8970-c86654fab9b1)

**Comment by sjordan29** [comment]
A comparison for the fine mesh with code updates. Seems like 30 s should be a fine option:

![image](https://github.com/EcohydrologyTeam/ClearWater-riverine/assets/32182441/54802409-8688-4627-aacc-fcacbe1fcf2e)

@jrutyna - what do you think? Am I good to close this issue and issue a PR?

**Comment by jrutyna** [comment]
Do you have a revised "comparison_df_pXY_updates.csv" file for each of these simulations that I can review? Or let me know which notebook I can created it from.
