### ISSUE TITLE
Modify `postproc_utils` module to work with multiple constituents

### ISSUE THREAD

**Issue by sjordan29** [EcohydrologyTeam/ClearWater-riverine#76]
Update the postprocessing utilities so that they will work with the refactored code that allows for running multiple constituents (#51, #75). 

The `simulation` previously contained the `mass_flux_total` in the simulation's model `mesh`. Now, each individual constituent has its own `total_mass_flux` that can be accessed with `simulation.constituent_name.mass_flux`. I'm envisioning that the  `_mass_bal_global` function will now have two inputs: `simulation` and `constituent`, which would be a string of the name of the constituent that you want to run the postprocessing utilities on.

**Comment by jrutyna** [comment]
The postprocessing utilities have been updated to work with a named constituent. Please see this commit: 73148c11f707c75d6e68aeb6904b81b7628133b2
